apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: core.harbor.domain/backbase/registry:1.8.0
          imagePullPolicy: "Never"